version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - moltin-graphql-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - moltin-graphql-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: moltin-graphql-{{ checksum "package.json" }}
      - run:
          command: node -r dotenv/config src
          background: true
workflows:
  version: 2
  build:
    jobs:
      - build
